import { formatValue } from '../format.js';
import { nameToCssVar } from '../name.js';
import type { AllSnapshots, Variable, VariableCollection } from '../types.js';
import { effectStyleDeclarations } from './effects.js';

const HEADER = `/* Auto-generated by @leta/cli — DO NOT EDIT.
 * Source: Figma Library variables.
 * Run \`pnpm tokens:sync\` to regenerate.
 */
`;

interface ModeBlock {
  selectorOrAtRule: string; // e.g. ":root" or "[data-theme=\"dark\"]" or "@media (max-width: 1023px)"
  isMediaQuery: boolean;
  declarations: string[];
}

/**
 * Emit a ModeBlock's CSS, indented one level if it's wrapped in a media query.
 */
function renderBlock(block: ModeBlock): string {
  if (!block.isMediaQuery) {
    return `${block.selectorOrAtRule} {\n${block.declarations.map((d) => `  ${d}`).join('\n')}\n}\n`;
  }
  // Media queries wrap a :root block.
  const inner = block.declarations.map((d) => `    ${d}`).join('\n');
  return `${block.selectorOrAtRule} {\n  :root {\n${inner}\n  }\n}\n`;
}

/**
 * Serialize a single collection's variables as `--name: value;` lines for one mode.
 */
function declarationsForMode(
  collection: VariableCollection,
  modeId: string,
  snapshots: AllSnapshots,
): string[] {
  const lines: string[] = [];
  for (const v of collection.variables) {
    const val = v.valuesByMode[modeId];
    if (val === undefined) continue; // Variable has no value in this mode (shouldn't happen, but guard)
    lines.push(`${nameToCssVar(v.name)}: ${formatValue(val, v, snapshots)};`);
  }
  return lines;
}

/**
 * Map breakpoint mode names to media-query prelude strings.
 *
 * Mapped Type & Mapped Sizes use Desktop (default), Tablet, Mobile.
 * Convention: emit Desktop in :root (no @media), Tablet under `@media (max-width: 1023px)`,
 * and Mobile under `@media (max-width: 767px)` so the cascade lands correctly.
 */
const BREAKPOINT_MEDIA: Record<string, string> = {
  Tablet: '@media (max-width: 1023px)',
  Mobile: '@media (max-width: 767px)',
};

/** Build all blocks emitted in tokens.css. */
function buildBlocks(snapshots: AllSnapshots): ModeBlock[] {
  const blocks: ModeBlock[] = [];

  // === :root — defaults from every collection in their default mode ===
  const rootDeclarations: string[] = [];
  rootDeclarations.push('/* Brand primitives */');
  rootDeclarations.push(...declarationsForMode(snapshots.brand, snapshots.brand.defaultModeId, snapshots));

  rootDeclarations.push('', '/* Alias (semantic) — Product mode (only) */');
  // Alias has Product + Marketing modes; we emit only Product (per design decision).
  const productMode = snapshots.alias.modes.find((m) => m.name === 'Product');
  if (!productMode) throw new Error('Alias collection is missing the "Product" mode');
  rootDeclarations.push(...declarationsForMode(snapshots.alias, productMode.modeId, snapshots));

  rootDeclarations.push('', '/* Mapped Colors — Light Mode (default) */');
  const lightMode = snapshots.mappedColors.modes.find((m) => m.name === 'Light Mode');
  if (!lightMode) throw new Error('Mapped Colors is missing "Light Mode"');
  rootDeclarations.push(...declarationsForMode(snapshots.mappedColors, lightMode.modeId, snapshots));

  rootDeclarations.push('', '/* Mapped Type — Desktop (default) */');
  const typeDesktop = snapshots.mappedType.modes.find((m) => m.name === 'Desktop');
  if (!typeDesktop) throw new Error('Mapped Type is missing "Desktop" mode');
  rootDeclarations.push(...declarationsForMode(snapshots.mappedType, typeDesktop.modeId, snapshots));

  rootDeclarations.push('', '/* Mapped Sizes — Desktop (default) */');
  const sizesDesktop = snapshots.mappedSizes.modes.find((m) => m.name === 'Desktop');
  if (!sizesDesktop) throw new Error('Mapped Sizes is missing "Desktop" mode');
  rootDeclarations.push(...declarationsForMode(snapshots.mappedSizes, sizesDesktop.modeId, snapshots));

  // Effect styles (drop shadows) — single-layer or multi-layer composed `box-shadow`.
  // These are file-level effect styles, not mode-bound, so they live in :root only.
  const shadowDecls = effectStyleDeclarations(snapshots.effectStyles.styles);
  if (shadowDecls.length > 0) {
    rootDeclarations.push('', '/* Effect styles — elevation drop shadows */');
    rootDeclarations.push(...shadowDecls);
  }

  blocks.push({ selectorOrAtRule: ':root', isMediaQuery: false, declarations: rootDeclarations });

  // === [data-theme="dark"] — Mapped Colors dark mode overrides ===
  const darkMode = snapshots.mappedColors.modes.find((m) => m.name === 'Dark Mode');
  if (darkMode) {
    blocks.push({
      selectorOrAtRule: '[data-theme="dark"]',
      isMediaQuery: false,
      declarations: declarationsForMode(snapshots.mappedColors, darkMode.modeId, snapshots),
    });
  }

  // === Breakpoint media queries — Mapped Type + Mapped Sizes ===
  for (const bpName of ['Tablet', 'Mobile'] as const) {
    const typeMode = snapshots.mappedType.modes.find((m) => m.name === bpName);
    const sizeMode = snapshots.mappedSizes.modes.find((m) => m.name === bpName);
    const decls: string[] = [];
    if (typeMode) {
      decls.push(`/* Mapped Type — ${bpName} */`);
      decls.push(...declarationsForMode(snapshots.mappedType, typeMode.modeId, snapshots));
    }
    if (sizeMode) {
      decls.push('', `/* Mapped Sizes — ${bpName} */`);
      decls.push(...declarationsForMode(snapshots.mappedSizes, sizeMode.modeId, snapshots));
    }
    if (decls.length > 0) {
      blocks.push({
        selectorOrAtRule: BREAKPOINT_MEDIA[bpName]!,
        isMediaQuery: true,
        declarations: decls,
      });
    }
  }

  return blocks;
}

export function generateCss(snapshots: AllSnapshots): string {
  const blocks = buildBlocks(snapshots);
  return HEADER + '\n' + blocks.map(renderBlock).join('\n');
}

/** Variables exposed (as CSS vars) for downstream Tailwind / TS consumers. */
export function listAllVariables(snapshots: AllSnapshots): Variable[] {
  return [
    ...snapshots.brand.variables,
    ...snapshots.alias.variables,
    ...snapshots.mappedColors.variables,
    ...snapshots.mappedType.variables,
    ...snapshots.mappedSizes.variables,
  ];
}
