import { slugify, nameToCssVar } from '../name.js';
import type { AllSnapshots, Variable } from '../types.js';

const HEADER = `/* Auto-generated by @leta/cli — DO NOT EDIT.
 * Tailwind preset that exposes design tokens as theme keys. Every value is a
 * CSS \`var(--token)\` reference so theme/breakpoint switching works at runtime.
 * Run \`pnpm tokens:sync\` to regenerate.
 */
`;

interface Bucket {
  /** Tailwind theme key (e.g. "colors", "spacing"). */
  themeKey: string;
  /** Predicate that decides whether a variable belongs in this bucket. */
  match: (v: Variable) => boolean;
  /** Strip a leading category from the slug so Tailwind keys are concise. */
  trimPrefix?: string;
}

const BUCKETS: Bucket[] = [
  // Colors — every COLOR-typed variable from any collection lands here.
  { themeKey: 'colors', match: (v) => v.type === 'COLOR' },
  // Padding & spacing — Alias only; trimmed prefix.
  { themeKey: 'padding', match: (v) => v.name.startsWith('Padding/'), trimPrefix: 'padding-' },
  { themeKey: 'spacing', match: (v) => v.name.startsWith('Spacing/'), trimPrefix: 'spacing-' },
  // Border radius — Alias `Rounding/`.
  { themeKey: 'borderRadius', match: (v) => v.name.startsWith('Rounding/'), trimPrefix: 'rounding-' },
  // Border width — Alias `Stroke/`.
  { themeKey: 'borderWidth', match: (v) => v.name.startsWith('Stroke/'), trimPrefix: 'stroke-' },
  // Opacity — Alias `Opacity/`.
  { themeKey: 'opacity', match: (v) => v.name.startsWith('Opacity/'), trimPrefix: 'opacity-' },
  // Font size — Brand `Fonts/Size/` (Alias also has `Fonts/...` but those are font family/weight).
  {
    themeKey: 'fontSize',
    match: (v) => v.name.startsWith('Fonts/Size/'),
    trimPrefix: 'fonts-size-',
  },
  // Line height — Brand `Fonts/LineHeight/`.
  {
    themeKey: 'lineHeight',
    match: (v) => v.name.startsWith('Fonts/LineHeight/'),
    trimPrefix: 'fonts-lineheight-',
  },
  // Letter spacing — Brand `Fonts/Kerning/`.
  {
    themeKey: 'letterSpacing',
    match: (v) => v.name.startsWith('Fonts/Kerning/'),
    trimPrefix: 'fonts-kerning-',
  },
];

function listAllVars(snapshots: AllSnapshots): Variable[] {
  return [
    ...snapshots.brand.variables,
    ...snapshots.alias.variables,
    ...snapshots.mappedColors.variables,
    ...snapshots.mappedType.variables,
    ...snapshots.mappedSizes.variables,
  ];
}

export function generateTailwindPreset(snapshots: AllSnapshots): string {
  const allVars = listAllVars(snapshots);
  const themeExtend: Record<string, Record<string, string>> = {};

  for (const v of allVars) {
    for (const bucket of BUCKETS) {
      if (!bucket.match(v)) continue;
      let key = slugify(v.name);
      if (bucket.trimPrefix && key.startsWith(bucket.trimPrefix)) {
        key = key.slice(bucket.trimPrefix.length);
      }
      const cssVar = nameToCssVar(v.name);
      const bucketMap = (themeExtend[bucket.themeKey] ??= {});
      // Only first matching bucket wins per variable (predicates are mutually exclusive in practice).
      if (!bucketMap[key]) {
        bucketMap[key] = `var(${cssVar})`;
      }
      break;
    }
  }

  const themeJson = JSON.stringify({ extend: themeExtend }, null, 2);

  return `${HEADER}
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: ${indent(themeJson, 2)},
};
`;
}

/** Indent every line of `s` by `n` spaces (skip the first). */
function indent(s: string, n: number): string {
  const pad = ' '.repeat(n);
  return s
    .split('\n')
    .map((line, i) => (i === 0 ? line : pad + line))
    .join('\n');
}
