import { slugify } from '../name.js';
import { nameToCssVar } from '../name.js';
import type { AllSnapshots, TextStyle } from '../types.js';

const HEADER = `/* Auto-generated by @leta/cli — DO NOT EDIT.
 * Text style utility classes composed from Mapped Type tokens.
 * Run \`pnpm tokens:sync\` to regenerate.
 */

/* Prevent macOS subpixel antialiasing from making Inter Variable appear
 * heavier than its declared font-weight. Without this, font-weight:600
 * renders at ~800-900 weight on Retina displays — Figma uses antialiased
 * rendering so this aligns browser output with the design source of truth. */
html {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`;

const WEIGHT_MAP: Record<string, number> = {
  Thin: 100, ExtraLight: 200, Light: 300, Regular: 400,
  Medium: 500, SemiBold: 600, Bold: 700, ExtraBold: 800, Black: 900,
};

/**
 * Build a CSS class for a single text style.
 *
 * Each text style binds these properties to variables:
 *   fontFamily, fontStyle (weight), fontSize, lineHeight, letterSpacing
 *
 * For each bound property, emit `var(--target)` so the cascade picks up the
 * breakpoint-driven value. Properties without a bound variable fall through to
 * the literal value Figma reports.
 */
function normalizeStyleName(name: string): string {
  return name
    .replace(/\bSemBold\b/g, 'SemiBold')
    .replace(/\bSemi Bold\b/g, 'SemiBold');
}

function classForStyle(style: TextStyle, snapshots: AllSnapshots): string {
  const className = `.text-${slugify(normalizeStyleName(style.name))}`;
  const decls: string[] = [];

  // font-family (string)
  const familyAlias = style.boundVariables?.fontFamily;
  if (familyAlias) {
    const target = snapshots.variableIndex.get(familyAlias.id);
    if (target) decls.push(`font-family: var(${nameToCssVar(target.name)});`);
  } else {
    decls.push(`font-family: ${JSON.stringify(style.fontName.family)};`);
  }

  // font-weight (string in Figma — "Bold", "SemiBold", etc — mapped to a CSS value via the variable)
  const weightAlias = style.boundVariables?.fontStyle;
  if (weightAlias) {
    const target = snapshots.variableIndex.get(weightAlias.id);
    if (target) {
      decls.push(`font-weight: var(${nameToCssVar(target.name)});`);
    } else {
      decls.push(`font-weight: ${WEIGHT_MAP[style.fontName.style] ?? 400};`);
    }
  } else {
    decls.push(`font-weight: ${WEIGHT_MAP[style.fontName.style] ?? 400};`);
  }

  // font-size
  const sizeAlias = style.boundVariables?.fontSize;
  if (sizeAlias) {
    const target = snapshots.variableIndex.get(sizeAlias.id);
    if (target) {
      decls.push(`font-size: var(${nameToCssVar(target.name)});`);
    } else {
      decls.push(`font-size: ${style.fontSize}px;`);
    }
  } else {
    decls.push(`font-size: ${style.fontSize}px;`);
  }

  // line-height
  const lhAlias = style.boundVariables?.lineHeight;
  if (lhAlias) {
    const target = snapshots.variableIndex.get(lhAlias.id);
    if (target) {
      decls.push(`line-height: var(${nameToCssVar(target.name)});`);
    } else if (style.lineHeight.unit === 'PIXELS') {
      decls.push(`line-height: ${style.lineHeight.value}px;`);
    } else if (style.lineHeight.unit === 'PERCENT') {
      decls.push(`line-height: ${style.lineHeight.value}%;`);
    }
  } else if (style.lineHeight.unit === 'PIXELS') {
    decls.push(`line-height: ${style.lineHeight.value}px;`);
  } else if (style.lineHeight.unit === 'PERCENT') {
    decls.push(`line-height: ${style.lineHeight.value}%;`);
  }

  // letter-spacing
  const lsAlias = style.boundVariables?.letterSpacing;
  if (lsAlias) {
    const target = snapshots.variableIndex.get(lsAlias.id);
    if (target) {
      decls.push(`letter-spacing: var(${nameToCssVar(target.name)});`);
    } else if (style.letterSpacing.unit === 'PIXELS' && style.letterSpacing.value !== 0) {
      decls.push(`letter-spacing: ${style.letterSpacing.value}px;`);
    }
  } else if (style.letterSpacing.unit === 'PIXELS' && style.letterSpacing.value !== 0) {
    decls.push(`letter-spacing: ${style.letterSpacing.value}px;`);
  }

  // textCase / textDecoration if non-default
  if (style.textCase && style.textCase !== 'ORIGINAL') {
    const cssCase = ({
      UPPER: 'uppercase',
      LOWER: 'lowercase',
      TITLE: 'capitalize',
      SMALL_CAPS: 'small-caps',
    } as Record<string, string>)[style.textCase];
    if (cssCase) decls.push(`text-transform: ${cssCase};`);
  }
  if (style.textDecoration && style.textDecoration !== 'NONE') {
    decls.push(`text-decoration: ${style.textDecoration.toLowerCase()};`);
  }

  return `${className} {\n${decls.map((d) => `  ${d}`).join('\n')}\n}`;
}

export function generateTextStylesCss(snapshots: AllSnapshots): string {
  const classes = snapshots.textStyles.styles.map((s) => classForStyle(s, snapshots));
  return HEADER + '\n' + classes.join('\n\n') + '\n';
}
