import { slugify } from '../name.js';
import type { AllSnapshots, Variable } from '../types.js';
import { listAllVariables } from './css.js';
import { effectStyleNameToCssVar } from './effects.js';

const HEADER = `/* Auto-generated by @leta/cli — DO NOT EDIT.
 * TypeScript token constants. Each entry is the CSS custom property name
 * (e.g. "--color-primary-default") that resolves at runtime.
 * Run \`pnpm tokens:sync\` to regenerate.
 */
`;

/**
 * Generate a TS module that exposes every token by its slug as a string
 * mapping to its CSS custom-property name. Components can use these via
 * `style={{ color: \`var(${tokens.colorPrimaryDefault})\` }}` if they want to
 * reference tokens dynamically without string-templating.
 */
export function generateTokensTs(snapshots: AllSnapshots): string {
  const all: Variable[] = listAllVariables(snapshots);

  const entries: { camelKey: string; cssVar: string; originalName: string }[] = all.map((v) => {
    const slug = slugify(v.name);
    return { camelKey: slugToCamel(slug), cssVar: `--${slug}`, originalName: v.name };
  });

  // Effect styles → shadow tokens (e.g. "Neutral Drop Shadow 3" → shadowNeutral3)
  for (const s of snapshots.effectStyles.styles) {
    const cssVar = effectStyleNameToCssVar(s.name);
    const camelKey = slugToCamel(cssVar.slice(2)); // drop leading "--"
    entries.push({ camelKey, cssVar, originalName: s.name });
  }

  // Dedupe in case two entries slugify to the same key (shouldn't happen, but be safe).
  const seen = new Map<string, string>();
  for (const e of entries) {
    if (seen.has(e.camelKey)) {
      throw new Error(
        `Duplicate token key "${e.camelKey}": ${seen.get(e.camelKey)} vs ${e.originalName}`,
      );
    }
    seen.set(e.camelKey, e.originalName);
  }

  const lines = entries.map((e) => `  /** ${e.originalName} */\n  ${e.camelKey}: '${e.cssVar}',`);

  return (
    HEADER +
    `\nexport const tokens = {\n${lines.join('\n')}\n} as const;\n\nexport type TokenKey = keyof typeof tokens;\n`
  );
}

function slugToCamel(slug: string): string {
  return slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}
